### ISSUE TITLE
Step 3 Error

### ISSUE THREAD

**Issue by paydana** [aron-tn/CC-Checker#4]
[+] Step 3 : Started ....
{'success': False, 'err': 'Invalid security token.'}
Traceback (most recent call last):
  File "Checker.py", line 108, in <module>
    funct(cc,mm,yy,cvv)
  File "Checker.py", line 49, in funct
    client=str(amir['clientSecret'])
KeyError: 'clientSecret'

**Comment by viiralelite** [comment]
i got this too

**Comment by maxibrainz10** [comment]
Me too

**Comment by iliaslb** [comment]
Same issue for me

**Comment by XMVZ** [comment]
same here

**Comment by aliafshany** [comment]
same
